language: go
sudo: required
go:
  - "1.14.x"

before_script:
  - go get github.com/mattn/goveralls
  - wget https://releases.hashicorp.com/consul/1.8.4/consul_1.8.4_linux_amd64.zip -O /tmp/consul.zip
  - wget https://s3.amazonaws.com/bitly-downloads/nsq/nsq-1.1.0.linux-amd64.go1.10.3.tar.gz -O /tmp/nsq.tar.gz
  - tar -xvf /tmp/nsq.tar.gz
  - export PATH=$PATH:$PWD/nsq-1.1.0.linux-amd64.go1.10.3/bin/
  - unzip /tmp/consul.zip
  - export PATH=$PATH:$PWD/consul
  

notifications:
  email: false

script:
  - test -z "$(gofmt -s -l . | tee /dev/stderr)"
  - go test -v ./... -timeout 1m
  - $GOPATH/bin/goveralls -service=travis-ci
