version: "3"
services:
  panoptes:
    build: .
    image: panoptes-stream:latest
    volumes:
      - ./scripts/demo/influxdb:/etc/panoptes
    command: ["-config", "/etc/panoptes/panoptes.yml"]
    ports:
      - "8081:8081"

  grafana:
    image: "grafana/grafana"
    volumes:
      - ./scripts/demo/influxdb:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=panoptes
      - GF_SECURITY_ADMIN_PASSWORD=panoptes

  influxdb:
    image: "influxdb"
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=mydb
