version: "3"
services:
  panoptes:
    build: .
    image: panoptes-stream:latest
    volumes:
      - ./scripts/demo:/etc/panoptes
    command: ["-config", "/etc/panoptes/panoptes.yml"]
    ports:
      - "8081:8081"
  simulator:
    image: panoptes-stream:latest
    entrypoint: ["/usr/bin/simulator", "-interval", "5"]

  grafana:
    image: "grafana/grafana"
    volumes:
      - ./scripts/demo/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./scripts/demo/grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=panoptes
      - GF_SECURITY_ADMIN_PASSWORD=panoptes

  influxdb:
    image: "influxdb"
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=mydb
