global:
  datacenter: VMDC

ui:
  service:
    type: "LoadBalancer"

connectInject:
  enabled: false

client:
  enabled: true
  grpc: true

server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
