devices:
  - host: core1.nbc
    tlscert: /etc/cert/file.crt
    tlskey: /etc/cert/file.key
    sensors:
      - sensor1
      - sensor2
      - sensor3

sensors:
  sensor1:
    path: /interfaces/interface/state
    mode: on_change
    service: juniper.gnmi
  sensor2:
    path: /interfaces/interface
    mode: on_change
    service: juniper.gnmi
  sensor3:
    path: /interfaces/interface
    mode: on_change
    service: cisco.gnmi

redial: 5
