devices:
  - host: core1.nca:50051
    tlsCertFile: /etc/cert/file.crt
    tlsKeyFile: /etc/cert/file.key
    caFile: /etc/cert/ca.crt
    sensors:
      - sensor2

sensors:
  sensor1:
    path: /interfaces/interface/state
    mode: on_change
    service: juniper.gnmi
    output: kafka1::panoptes
  sensor2:
    path: /interfaces/interface/state/counters/
    mode: sample
    interval: 10
    service: juniper.jti
    output: console::stdout
  sensor3:
    path: /network-instances/network-instance/
    mode: sample
    interval: 10
    service: juniper.jti
    output: kafka1::bgp

producers:
  kafka1:
    service: kafka
    configFile: etc/kafka.yaml
  console:
    service: console

logger:
  level: "debug"
  encoding: console
  outputPaths:
    - stdout
  errorOutputPaths:
    - stderr
