devices:
  - host: core1.nca:50051
    tlsCertFile: /etc/cert/file.crt
    tlsKeyFile: /etc/cert/file.key
    caFile: /etc/cert/ca.crt
    sensors:
      - sensor1
      - sensor2

sensors:
  sensor1:
    path: /interfaces/interface/state
    mode: on_change
    service: juniper.gnmi
    output: kafka1::panoptes
  sensor2:
    path: /interfaces/interface/state/counters
    mode: sample
    service: juniper.gnmi
    output: kafka1::panoptes

producers:
  kafka1:
    configFile: etc/kafka.yaml
