version: "3"
services:
  panoptes:
    image: panoptes-stream:latest
    container_name: panoptes-node
    depends_on:
      - simulator
      - kafka
    volumes:
      - ./:/etc/panoptes
    command: ["-config", "/etc/panoptes/panoptes-kafka.yml"]
    ports:
      - "8081:8081"
  simulator:
    image: panoptes-stream:latest
    container_name: panoptes-simulator
    entrypoint: ["/usr/bin/simulator", "-interval", "5"]

  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: "bitnami/kafka:latest"
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
