version: "3"
services:
  panoptes-node1:
    image: panoptes-stream:latest
    container_name: panoptes-node1
    volumes:
      - ./:/etc/panoptes
    command: ["-config", "/etc/panoptes/config.yml"]
    networks:
      - demo-net

  panoptes-node2:
    image: panoptes-stream:latest
    container_name: panoptes-node2
    volumes:
      - ./:/etc/panoptes
    command: ["-config", "/etc/panoptes/config.yml"]
    networks:
      - demo-net
  simulator:
    image: panoptes-stream:latest
    container_name: panoptes-simulator
    entrypoint: ["/usr/bin/simulator", "-interval", "5"]
    networks:
      demo-net:
        aliases:
          - device1.lax
          - device2.lax
          - device3.lax
          - device4.lax
          - device5.lax

  grafana:
    image: "grafana/grafana"
    container_name: grafana
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=panoptes
      - GF_SECURITY_ADMIN_PASSWORD=panoptes
    networks:
      - demo-net

  influxdb:
    image: "influxdb"
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=mybucket
    networks:
      - demo-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - demo-net

networks:
  demo-net:
