{{- if eq .Values.configuration "consul" }} 
apiVersion: batch/v1
kind: Job
metadata:
  name: panoptes-job
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"

spec:
  template:
    metadata:
      name: panoptes-job
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install-job
        image: consul
        command:
          - '/bin/sh'
          - '-ec'
          - |
            cat /etc/panoptes/global.json | consul kv put panoptes/config/global -
            consul kv put panoptes/config/devices/
            consul kv put panoptes/config/sensors/
            consul kv put panoptes/config/databases/
            consul kv put panoptes/config/producers/
        env:
          - name: HOST_IP
            valueFrom:
                fieldRef:
                    fieldPath: status.hostIP
          - name: CONSUL_HTTP_ADDR 
            value: "$(HOST_IP):8500"     
        volumeMounts:
          - name: config
            mountPath: /etc/panoptes    

      volumes:
        - name: config
          configMap:
            name: panoptes-global
{{- end }}                  