apiVersion: v1
kind: Service
metadata:
  name: panoptes-stream
  labels:
    name: panoptes-stream
spec:
  clusterIP: None
  ports:
    - name: status
      port: {{ .Values.statusPort}}
      targetPort: {{ .Values.statusPort}}   
  selector:
    app: panoptes-stream
