apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: panoptes
  labels:
    app: panoptes
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: panoptes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: panoptes
subjects:
  - kind: ServiceAccount
    name: panoptes
    namespace: {{ .Values.namespace}}