apiVersion: v1
kind: Service
metadata:
  name: panoptes-stream
  labels:
    name: panoptes-stream
spec:
  clusterIP: None
  ports:
    - name: status
      port: 8081
      targetPort: 8081   
  selector:
    app: panoptes-stream
