name: "panoptes-stream"

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test
        run: |
          wget -q https://releases.hashicorp.com/consul/1.8.4/consul_1.8.4_linux_amd64.zip -O /tmp/consul.zip
          wget -q https://s3.amazonaws.com/bitly-downloads/nsq/nsq-1.1.0.linux-amd64.go1.10.3.tar.gz -O /tmp/nsq.tar.gz
          tar -xvf /tmp/nsq.tar.gz
          export PATH=$PATH:$PWD/nsq-1.1.0.linux-amd64.go1.10.3/bin/
          unzip /tmp/consul.zip
          export PATH=$PATH:$PWD
          go test ./... -timeout 5m -coverprofile=profile.cov

      - name: Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
